# Adapted from to https://apps.timwhitlock.info/emoji/tables/unicode

codes = {"grinning face with smiling eyes": b'\xf0\x9f\x98\x81',
         "face with tears of joy": b'\xf0\x9f\x98\x82',
         "smiling face with open mouth": b'\xf0\x9f\x98\x83',
         "smiling face with open mouth and smiling eyes": b'\xf0\x9f\x98\x84',
         "smiling face with open mouth and cold sweat": b'\xf0\x9f\x98\x85',
         "smiling face with open mouth and tightly-closed eyes": b'\xf0\x9f\x98\x86',
         "winking face": b'\xf0\x9f\x98\x89',
         "smiling face with smiling eyes": b'\xf0\x9f\x98\x8a',
         "face savouring delicious food": b'\xf0\x9f\x98\x8b',
         "relieved face": b'\xf0\x9f\x98\x8c',
         "smiling face with heart-shaped eyes": b'\xf0\x9f\x98\x8d',
         "smirking face": b'\xf0\x9f\x98\x8f',
         "unamused face": b'\xf0\x9f\x98\x92',
         "face with cold sweat": b'\xf0\x9f\x98\x93',
         "pensive face": b'\xf0\x9f\x98\x94',
         "confounded face": b'\xf0\x9f\x98\x96',
         "face throwing a kiss": b'\xf0\x9f\x98\x98',
         "kissing face with closed eyes": b'\xf0\x9f\x98\x9a',
         "face with stuck-out tongue and winking eye": b'\xf0\x9f\x98\x9c',
         "face with stuck-out tongue and tightly-closed eyes": b'\xf0\x9f\x98\x9d',
         "disappointed face": b'\xf0\x9f\x98\x9e',
         "angry face": b'\xf0\x9f\x98\xa0',
         "pouting face": b'\xf0\x9f\x98\xa1',
         "crying face": b'\xf0\x9f\x98\xa2',
         "persevering face": b'\xf0\x9f\x98\xa3',
         "face with look of triumph": b'\xf0\x9f\x98\xa4',
         "disappointed but relieved face": b'\xf0\x9f\x98\xa5',
         "fearful face": b'\xf0\x9f\x98\xa8',
         "weary face": b'\xf0\x9f\x98\xa9',
         "sleepy face": b'\xf0\x9f\x98\xaa',
         "tired face": b'\xf0\x9f\x98\xab',
         "loudly crying face": b'\xf0\x9f\x98\xad',
         "face with open mouth and cold sweat": b'\xf0\x9f\x98\xb0',
         "face screaming in fear": b'\xf0\x9f\x98\xb1',
         "astonished face": b'\xf0\x9f\x98\xb2',
         "flushed face": b'\xf0\x9f\x98\xb3',
         "dizzy face": b'\xf0\x9f\x98\xb5',
         "face with medical mask": b'\xf0\x9f\x98\xb7',
         "grinning cat face with smiling eyes": b'\xf0\x9f\x98\xb8',
         "cat face with tears of joy": b'\xf0\x9f\x98\xb9',
         "smiling cat face with open mouth": b'\xf0\x9f\x98\xba',
         "smiling cat face with heart-shaped eyes": b'\xf0\x9f\x98\xbb',
         "cat face with wry smile": b'\xf0\x9f\x98\xbc',
         "kissing cat face with closed eyes": b'\xf0\x9f\x98\xbd',
         "pouting cat face": b'\xf0\x9f\x98\xbe',
         "crying cat face": b'\xf0\x9f\x98\xbf',
         "weary cat face": b'\xf0\x9f\x99\x80',
         "face with no good gesture": b'\xf0\x9f\x99\x85',
         "face with ok gesture": b'\xf0\x9f\x99\x86',
         "person bowing deeply": b'\xf0\x9f\x99\x87',
         "see-no-evil monkey": b'\xf0\x9f\x99\x88',
         "hear-no-evil monkey": b'\xf0\x9f\x99\x89',
         "speak-no-evil monkey": b'\xf0\x9f\x99\x8a',
         "happy person raising one hand": b'\xf0\x9f\x99\x8b',
         "person raising both hands in celebration": b'\xf0\x9f\x99\x8c',
         "person frowning": b'\xf0\x9f\x99\x8d',
         "person with pouting face": b'\xf0\x9f\x99\x8e',
         "person with folded hands": b'\xf0\x9f\x99\x8f',
         "black scissors": b'\xe2\x9c\x82',
         "white heavy check mark": b'\xe2\x9c\x85',
         "airplane": b'\xe2\x9c\x88',
         "envelope": b'\xe2\x9c\x89',
         "raised fist": b'\xe2\x9c\x8a',
         "raised hand": b'\xe2\x9c\x8b',
         "victory hand": b'\xe2\x9c\x8c',
         "pencil": b'\xe2\x9c\x8f',
         "black nib": b'\xe2\x9c\x92',
         "heavy check mark": b'\xe2\x9c\x94',
         "heavy multiplication x": b'\xe2\x9c\x96',
         "sparkles": b'\xe2\x9c\xa8',
         "eight spoked asterisk": b'\xe2\x9c\xb3',
         "eight pointed black star": b'\xe2\x9c\xb4',
         "snowflake": b'\xe2\x9d\x84',
         "sparkle": b'\xe2\x9d\x87',
         "cross mark": b'\xe2\x9d\x8c',
         "negative squared cross mark": b'\xe2\x9d\x8e',
         "black question mark ornament": b'\xe2\x9d\x93',
         "white question mark ornament": b'\xe2\x9d\x94',
         "white exclamation mark ornament": b'\xe2\x9d\x95',
         "heavy exclamation mark symbol": b'\xe2\x9d\x97',
         "heavy black heart": b'\xe2\x9d\xa4',
         "heavy plus sign": b'\xe2\x9e\x95',
         "heavy minus sign": b'\xe2\x9e\x96',
         "heavy division sign": b'\xe2\x9e\x97',
         "black rightwards arrow": b'\xe2\x9e\xa1',
         "curly loop": b'\xe2\x9e\xb0',
         "rocket": b'\xf0\x9f\x9a\x80',
         "railway car": b'\xf0\x9f\x9a\x83',
         "high-speed train": b'\xf0\x9f\x9a\x84',
         "high-speed train with bullet nose": b'\xf0\x9f\x9a\x85',
         "metro": b'\xf0\x9f\x9a\x87',
         "station": b'\xf0\x9f\x9a\x89',
         "bus": b'\xf0\x9f\x9a\x8c',
         "bus stop": b'\xf0\x9f\x9a\x8f',
         "ambulance": b'\xf0\x9f\x9a\x91',
         "fire engine": b'\xf0\x9f\x9a\x92',
         "police car": b'\xf0\x9f\x9a\x93',
         "taxi": b'\xf0\x9f\x9a\x95',
         "automobile": b'\xf0\x9f\x9a\x97',
         "recreational vehicle": b'\xf0\x9f\x9a\x99',
         "delivery truck": b'\xf0\x9f\x9a\x9a',
         "ship": b'\xf0\x9f\x9a\xa2',
         "speedboat": b'\xf0\x9f\x9a\xa4',
         "horizontal traffic light": b'\xf0\x9f\x9a\xa5',
         "construction sign": b'\xf0\x9f\x9a\xa7',
         "police cars revolving light": b'\xf0\x9f\x9a\xa8',
         "triangular flag on post": b'\xf0\x9f\x9a\xa9',
         "door": b'\xf0\x9f\x9a\xaa',
         "no entry sign": b'\xf0\x9f\x9a\xab',
         "smoking symbol": b'\xf0\x9f\x9a\xac',
         "no smoking symbol": b'\xf0\x9f\x9a\xad',
         "bicycle": b'\xf0\x9f\x9a\xb2',
         "pedestrian": b'\xf0\x9f\x9a\xb6',
         "mens symbol": b'\xf0\x9f\x9a\xb9',
         "womens symbol": b'\xf0\x9f\x9a\xba',
         "restroom": b'\xf0\x9f\x9a\xbb',
         "baby symbol": b'\xf0\x9f\x9a\xbc',
         "toilet": b'\xf0\x9f\x9a\xbd',
         "water closet": b'\xf0\x9f\x9a\xbe',
         "bath": b'\xf0\x9f\x9b\x80',
         "circled latin capital letter m": b'\xe2\x93\x82',
         "negative squared latin capital letter a": b'\xf0\x9f\x85\xb0',
         "negative squared latin capital letter b": b'\xf0\x9f\x85\xb1',
         "negative squared latin capital letter o": b'\xf0\x9f\x85\xbe',
         "negative squared latin capital letter p": b'\xf0\x9f\x85\xbf',
         "negative squared ab": b'\xf0\x9f\x86\x8e',
         "squared cl": b'\xf0\x9f\x86\x91',
         "squared cool": b'\xf0\x9f\x86\x92',
         "squared free": b'\xf0\x9f\x86\x93',
         "squared id": b'\xf0\x9f\x86\x94',
         "squared new": b'\xf0\x9f\x86\x95',
         "squared ng": b'\xf0\x9f\x86\x96',
         "squared ok": b'\xf0\x9f\x86\x97',
         "squared sos": b'\xf0\x9f\x86\x98',
         "squared up with exclamation mark": b'\xf0\x9f\x86\x99',
         "squared vs": b'\xf0\x9f\x86\x9a',
         "regional indicator symbol letter d + regional indicator symbol letter e": b'\xf0\x9f\x87\xa9\xf0\x9f\x87\xaa',
         "regional indicator symbol letter g + regional indicator symbol letter b": b'\xf0\x9f\x87\xac\xf0\x9f\x87\xa7',
         "regional indicator symbol letter c + regional indicator symbol letter n": b'\xf0\x9f\x87\xa8\xf0\x9f\x87\xb3',
         "regional indicator symbol letter j + regional indicator symbol letter p": b'\xf0\x9f\x87\xaf\xf0\x9f\x87\xb5',
         "regional indicator symbol letter f + regional indicator symbol letter r": b'\xf0\x9f\x87\xab\xf0\x9f\x87\xb7',
         "regional indicator symbol letter k + regional indicator symbol letter r": b'\xf0\x9f\x87\xb0\xf0\x9f\x87\xb7',
         "regional indicator symbol letter e + regional indicator symbol letter s": b'\xf0\x9f\x87\xaa\xf0\x9f\x87\xb8',
         "regional indicator symbol letter i + regional indicator symbol letter t": b'\xf0\x9f\x87\xae\xf0\x9f\x87\xb9',
         "regional indicator symbol letter r + regional indicator symbol letter u": b'\xf0\x9f\x87\xb7\xf0\x9f\x87\xba',
         "regional indicator symbol letter u + regional indicator symbol letter s": b'\xf0\x9f\x87\xba\xf0\x9f\x87\xb8',
         "squared katakana koko": b'\xf0\x9f\x88\x81',
         "squared katakana sa": b'\xf0\x9f\x88\x82',
         "squared cjk unified ideograph-7121": b'\xf0\x9f\x88\x9a',
         "squared cjk unified ideograph-6307": b'\xf0\x9f\x88\xaf',
         "squared cjk unified ideograph-7981": b'\xf0\x9f\x88\xb2',
         "squared cjk unified ideograph-7a7a": b'\xf0\x9f\x88\xb3',
         "squared cjk unified ideograph-5408": b'\xf0\x9f\x88\xb4',
         "squared cjk unified ideograph-6e80": b'\xf0\x9f\x88\xb5',
         "squared cjk unified ideograph-6709": b'\xf0\x9f\x88\xb6',
         "squared cjk unified ideograph-6708": b'\xf0\x9f\x88\xb7',
         "squared cjk unified ideograph-7533": b'\xf0\x9f\x88\xb8',
         "squared cjk unified ideograph-5272": b'\xf0\x9f\x88\xb9',
         "squared cjk unified ideograph-55b6": b'\xf0\x9f\x88\xba',
         "circled ideograph advantage": b'\xf0\x9f\x89\x90',
         "circled ideograph accept": b'\xf0\x9f\x89\x91',
         "copyright sign": b'\xc2\xa9',
         "registered sign": b'\xc2\xae',
         "double exclamation mark": b'\xe2\x80\xbc',
         "exclamation question mark": b'\xe2\x81\x89',
         "number sign + combining enclosing keycap": b'#\xe2\x83\xa3',
         "digit eight + combining enclosing keycap": b'8\xe2\x83\xa3',
         "digit nine + combining enclosing keycap": b'9\xe2\x83\xa3',
         "digit seven + combining enclosing keycap": b'7\xe2\x83\xa3',
         "digit zero + combining enclosing keycap": b'0\xe2\x83\xa3',
         "digit six + combining enclosing keycap": b'6\xe2\x83\xa3',
         "digit five + combining enclosing keycap": b'5\xe2\x83\xa3',
         "digit four + combining enclosing keycap": b'4\xe2\x83\xa3',
         "digit three + combining enclosing keycap": b'3\xe2\x83\xa3',
         "digit two + combining enclosing keycap": b'2\xe2\x83\xa3',
         "digit one + combining enclosing keycap": b'1\xe2\x83\xa3',
         "trade mark sign": b'\xe2\x84\xa2',
         "information source": b'\xe2\x84\xb9',
         "left right arrow": b'\xe2\x86\x94',
         "up down arrow": b'\xe2\x86\x95',
         "north west arrow": b'\xe2\x86\x96',
         "north east arrow": b'\xe2\x86\x97',
         "south east arrow": b'\xe2\x86\x98',
         "south west arrow": b'\xe2\x86\x99',
         "leftwards arrow with hook": b'\xe2\x86\xa9',
         "rightwards arrow with hook": b'\xe2\x86\xaa',
         "watch": b'\xe2\x8c\x9a',
         "hourglass": b'\xe2\x8c\x9b',
         "black right-pointing double triangle": b'\xe2\x8f\xa9',
         "black left-pointing double triangle": b'\xe2\x8f\xaa',
         "black up-pointing double triangle": b'\xe2\x8f\xab',
         "black down-pointing double triangle": b'\xe2\x8f\xac',
         "alarm clock": b'\xe2\x8f\xb0',
         "hourglass with flowing sand": b'\xe2\x8f\xb3',
         "black small square": b'\xe2\x96\xaa',
         "white small square": b'\xe2\x96\xab',
         "black right-pointing triangle": b'\xe2\x96\xb6',
         "black left-pointing triangle": b'\xe2\x97\x80',
         "white medium square": b'\xe2\x97\xbb',
         "black medium square": b'\xe2\x97\xbc',
         "white medium small square": b'\xe2\x97\xbd',
         "black medium small square": b'\xe2\x97\xbe',
         "black sun with rays": b'\xe2\x98\x80',
         "cloud": b'\xe2\x98\x81',
         "black telephone": b'\xe2\x98\x8e',
         "ballot box with check": b'\xe2\x98\x91',
         "umbrella with rain drops": b'\xe2\x98\x94',
         "hot beverage": b'\xe2\x98\x95',
         "white up pointing index": b'\xe2\x98\x9d',
         "white smiling face": b'\xe2\x98\xba',
         "aries": b'\xe2\x99\x88',
         "taurus": b'\xe2\x99\x89',
         "gemini": b'\xe2\x99\x8a',
         "cancer": b'\xe2\x99\x8b',
         "leo": b'\xe2\x99\x8c',
         "virgo": b'\xe2\x99\x8d',
         "libra": b'\xe2\x99\x8e',
         "scorpius": b'\xe2\x99\x8f',
         "sagittarius": b'\xe2\x99\x90',
         "capricorn": b'\xe2\x99\x91',
         "aquarius": b'\xe2\x99\x92',
         "pisces": b'\xe2\x99\x93',
         "black spade suit": b'\xe2\x99\xa0',
         "black club suit": b'\xe2\x99\xa3',
         "black heart suit": b'\xe2\x99\xa5',
         "black diamond suit": b'\xe2\x99\xa6',
         "hot springs": b'\xe2\x99\xa8',
         "black universal recycling symbol": b'\xe2\x99\xbb',
         "wheelchair symbol": b'\xe2\x99\xbf',
         "anchor": b'\xe2\x9a\x93',
         "warning sign": b'\xe2\x9a\xa0',
         "high voltage sign": b'\xe2\x9a\xa1',
         "medium white circle": b'\xe2\x9a\xaa',
         "medium black circle": b'\xe2\x9a\xab',
         "soccer ball": b'\xe2\x9a\xbd',
         "baseball": b'\xe2\x9a\xbe',
         "snowman without snow": b'\xe2\x9b\x84',
         "sun behind cloud": b'\xe2\x9b\x85',
         "ophiuchus": b'\xe2\x9b\x8e',
         "no entry": b'\xe2\x9b\x94',
         "church": b'\xe2\x9b\xaa',
         "fountain": b'\xe2\x9b\xb2',
         "flag in hole": b'\xe2\x9b\xb3',
         "sailboat": b'\xe2\x9b\xb5',
         "tent": b'\xe2\x9b\xba',
         "fuel pump": b'\xe2\x9b\xbd',
         "arrow pointing rightwards then curving upwards": b'\xe2\xa4\xb4',
         "arrow pointing rightwards then curving downwards": b'\xe2\xa4\xb5',
         "leftwards black arrow": b'\xe2\xac\x85',
         "upwards black arrow": b'\xe2\xac\x86',
         "downwards black arrow": b'\xe2\xac\x87',
         "black large square": b'\xe2\xac\x9b',
         "white large square": b'\xe2\xac\x9c',
         "white medium star": b'\xe2\xad\x90',
         "heavy large circle": b'\xe2\xad\x95',
         "wavy dash": b'\xe3\x80\xb0',
         "part alternation mark": b'\xe3\x80\xbd',
         "circled ideograph congratulation": b'\xe3\x8a\x97',
         "circled ideograph secret": b'\xe3\x8a\x99',
         "mahjong tile red dragon": b'\xf0\x9f\x80\x84',
         "playing card black joker": b'\xf0\x9f\x83\x8f',
         "cyclone": b'\xf0\x9f\x8c\x80',
         "foggy": b'\xf0\x9f\x8c\x81',
         "closed umbrella": b'\xf0\x9f\x8c\x82',
         "night with stars": b'\xf0\x9f\x8c\x83',
         "sunrise over mountains": b'\xf0\x9f\x8c\x84',
         "sunrise": b'\xf0\x9f\x8c\x85',
         "cityscape at dusk": b'\xf0\x9f\x8c\x86',
         "sunset over buildings": b'\xf0\x9f\x8c\x87',
         "rainbow": b'\xf0\x9f\x8c\x88',
         "bridge at night": b'\xf0\x9f\x8c\x89',
         "water wave": b'\xf0\x9f\x8c\x8a',
         "volcano": b'\xf0\x9f\x8c\x8b',
         "milky way": b'\xf0\x9f\x8c\x8c',
         "earth globe asia-australia": b'\xf0\x9f\x8c\x8f',
         "new moon symbol": b'\xf0\x9f\x8c\x91',
         "first quarter moon symbol": b'\xf0\x9f\x8c\x93',
         "waxing gibbous moon symbol": b'\xf0\x9f\x8c\x94',
         "full moon symbol": b'\xf0\x9f\x8c\x95',
         "crescent moon": b'\xf0\x9f\x8c\x99',
         "first quarter moon with face": b'\xf0\x9f\x8c\x9b',
         "glowing star": b'\xf0\x9f\x8c\x9f',
         "shooting star": b'\xf0\x9f\x8c\xa0',
         "chestnut": b'\xf0\x9f\x8c\xb0',
         "seedling": b'\xf0\x9f\x8c\xb1',
         "palm tree": b'\xf0\x9f\x8c\xb4',
         "cactus": b'\xf0\x9f\x8c\xb5',
         "tulip": b'\xf0\x9f\x8c\xb7',
         "cherry blossom": b'\xf0\x9f\x8c\xb8',
         "rose": b'\xf0\x9f\x8c\xb9',
         "hibiscus": b'\xf0\x9f\x8c\xba',
         "sunflower": b'\xf0\x9f\x8c\xbb',
         "blossom": b'\xf0\x9f\x8c\xbc',
         "ear of maize": b'\xf0\x9f\x8c\xbd',
         "ear of rice": b'\xf0\x9f\x8c\xbe',
         "herb": b'\xf0\x9f\x8c\xbf',
         "four leaf clover": b'\xf0\x9f\x8d\x80',
         "maple leaf": b'\xf0\x9f\x8d\x81',
         "fallen leaf": b'\xf0\x9f\x8d\x82',
         "leaf fluttering in wind": b'\xf0\x9f\x8d\x83',
         "mushroom": b'\xf0\x9f\x8d\x84',
         "tomato": b'\xf0\x9f\x8d\x85',
         "aubergine": b'\xf0\x9f\x8d\x86',
         "grapes": b'\xf0\x9f\x8d\x87',
         "melon": b'\xf0\x9f\x8d\x88',
         "watermelon": b'\xf0\x9f\x8d\x89',
         "tangerine": b'\xf0\x9f\x8d\x8a',
         "banana": b'\xf0\x9f\x8d\x8c',
         "pineapple": b'\xf0\x9f\x8d\x8d',
         "red apple": b'\xf0\x9f\x8d\x8e',
         "green apple": b'\xf0\x9f\x8d\x8f',
         "peach": b'\xf0\x9f\x8d\x91',
         "cherries": b'\xf0\x9f\x8d\x92',
         "strawberry": b'\xf0\x9f\x8d\x93',
         "hamburger": b'\xf0\x9f\x8d\x94',
         "slice of pizza": b'\xf0\x9f\x8d\x95',
         "meat on bone": b'\xf0\x9f\x8d\x96',
         "poultry leg": b'\xf0\x9f\x8d\x97',
         "rice cracker": b'\xf0\x9f\x8d\x98',
         "rice ball": b'\xf0\x9f\x8d\x99',
         "cooked rice": b'\xf0\x9f\x8d\x9a',
         "curry and rice": b'\xf0\x9f\x8d\x9b',
         "steaming bowl": b'\xf0\x9f\x8d\x9c',
         "spaghetti": b'\xf0\x9f\x8d\x9d',
         "bread": b'\xf0\x9f\x8d\x9e',
         "french fries": b'\xf0\x9f\x8d\x9f',
         "roasted sweet potato": b'\xf0\x9f\x8d\xa0',
         "dango": b'\xf0\x9f\x8d\xa1',
         "oden": b'\xf0\x9f\x8d\xa2',
         "sushi": b'\xf0\x9f\x8d\xa3',
         "fried shrimp": b'\xf0\x9f\x8d\xa4',
         "fish cake with swirl design": b'\xf0\x9f\x8d\xa5',
         "soft ice cream": b'\xf0\x9f\x8d\xa6',
         "shaved ice": b'\xf0\x9f\x8d\xa7',
         "ice cream": b'\xf0\x9f\x8d\xa8',
         "doughnut": b'\xf0\x9f\x8d\xa9',
         "cookie": b'\xf0\x9f\x8d\xaa',
         "chocolate bar": b'\xf0\x9f\x8d\xab',
         "candy": b'\xf0\x9f\x8d\xac',
         "lollipop": b'\xf0\x9f\x8d\xad',
         "custard": b'\xf0\x9f\x8d\xae',
         "honey pot": b'\xf0\x9f\x8d\xaf',
         "shortcake": b'\xf0\x9f\x8d\xb0',
         "bento box": b'\xf0\x9f\x8d\xb1',
         "pot of food": b'\xf0\x9f\x8d\xb2',
         "cooking": b'\xf0\x9f\x8d\xb3',
         "fork and knife": b'\xf0\x9f\x8d\xb4',
         "teacup without handle": b'\xf0\x9f\x8d\xb5',
         "sake bottle and cup": b'\xf0\x9f\x8d\xb6',
         "wine glass": b'\xf0\x9f\x8d\xb7',
         "cocktail glass": b'\xf0\x9f\x8d\xb8',
         "tropical drink": b'\xf0\x9f\x8d\xb9',
         "beer mug": b'\xf0\x9f\x8d\xba',
         "clinking beer mugs": b'\xf0\x9f\x8d\xbb',
         "ribbon": b'\xf0\x9f\x8e\x80',
         "wrapped present": b'\xf0\x9f\x8e\x81',
         "birthday cake": b'\xf0\x9f\x8e\x82',
         "jack-o-lantern": b'\xf0\x9f\x8e\x83',
         "christmas tree": b'\xf0\x9f\x8e\x84',
         "father christmas": b'\xf0\x9f\x8e\x85',
         "fireworks": b'\xf0\x9f\x8e\x86',
         "firework sparkler": b'\xf0\x9f\x8e\x87',
         "balloon": b'\xf0\x9f\x8e\x88',
         "party popper": b'\xf0\x9f\x8e\x89',
         "confetti ball": b'\xf0\x9f\x8e\x8a',
         "tanabata tree": b'\xf0\x9f\x8e\x8b',
         "crossed flags": b'\xf0\x9f\x8e\x8c',
         "pine decoration": b'\xf0\x9f\x8e\x8d',
         "japanese dolls": b'\xf0\x9f\x8e\x8e',
         "carp streamer": b'\xf0\x9f\x8e\x8f',
         "wind chime": b'\xf0\x9f\x8e\x90',
         "moon viewing ceremony": b'\xf0\x9f\x8e\x91',
         "school satchel": b'\xf0\x9f\x8e\x92',
         "graduation cap": b'\xf0\x9f\x8e\x93',
         "carousel horse": b'\xf0\x9f\x8e\xa0',
         "ferris wheel": b'\xf0\x9f\x8e\xa1',
         "roller coaster": b'\xf0\x9f\x8e\xa2',
         "fishing pole and fish": b'\xf0\x9f\x8e\xa3',
         "microphone": b'\xf0\x9f\x8e\xa4',
         "movie camera": b'\xf0\x9f\x8e\xa5',
         "cinema": b'\xf0\x9f\x8e\xa6',
         "headphone": b'\xf0\x9f\x8e\xa7',
         "artist palette": b'\xf0\x9f\x8e\xa8',
         "top hat": b'\xf0\x9f\x8e\xa9',
         "circus tent": b'\xf0\x9f\x8e\xaa',
         "ticket": b'\xf0\x9f\x8e\xab',
         "clapper board": b'\xf0\x9f\x8e\xac',
         "performing arts": b'\xf0\x9f\x8e\xad',
         "video game": b'\xf0\x9f\x8e\xae',
         "direct hit": b'\xf0\x9f\x8e\xaf',
         "slot machine": b'\xf0\x9f\x8e\xb0',
         "billiards": b'\xf0\x9f\x8e\xb1',
         "game die": b'\xf0\x9f\x8e\xb2',
         "bowling": b'\xf0\x9f\x8e\xb3',
         "flower playing cards": b'\xf0\x9f\x8e\xb4',
         "musical note": b'\xf0\x9f\x8e\xb5',
         "multiple musical notes": b'\xf0\x9f\x8e\xb6',
         "saxophone": b'\xf0\x9f\x8e\xb7',
         "guitar": b'\xf0\x9f\x8e\xb8',
         "musical keyboard": b'\xf0\x9f\x8e\xb9',
         "trumpet": b'\xf0\x9f\x8e\xba',
         "violin": b'\xf0\x9f\x8e\xbb',
         "musical score": b'\xf0\x9f\x8e\xbc',
         "running shirt with sash": b'\xf0\x9f\x8e\xbd',
         "tennis racquet and ball": b'\xf0\x9f\x8e\xbe',
         "ski and ski boot": b'\xf0\x9f\x8e\xbf',
         "basketball and hoop": b'\xf0\x9f\x8f\x80',
         "chequered flag": b'\xf0\x9f\x8f\x81',
         "snowboarder": b'\xf0\x9f\x8f\x82',
         "runner": b'\xf0\x9f\x8f\x83',
         "surfer": b'\xf0\x9f\x8f\x84',
         "trophy": b'\xf0\x9f\x8f\x86',
         "american football": b'\xf0\x9f\x8f\x88',
         "swimmer": b'\xf0\x9f\x8f\x8a',
         "house building": b'\xf0\x9f\x8f\xa0',
         "house with garden": b'\xf0\x9f\x8f\xa1',
         "office building": b'\xf0\x9f\x8f\xa2',
         "japanese post office": b'\xf0\x9f\x8f\xa3',
         "hospital": b'\xf0\x9f\x8f\xa5',
         "bank": b'\xf0\x9f\x8f\xa6',
         "automated teller machine": b'\xf0\x9f\x8f\xa7',
         "hotel": b'\xf0\x9f\x8f\xa8',
         "love hotel": b'\xf0\x9f\x8f\xa9',
         "convenience store": b'\xf0\x9f\x8f\xaa',
         "school": b'\xf0\x9f\x8f\xab',
         "department store": b'\xf0\x9f\x8f\xac',
         "factory": b'\xf0\x9f\x8f\xad',
         "izakaya lantern": b'\xf0\x9f\x8f\xae',
         "japanese castle": b'\xf0\x9f\x8f\xaf',
         "european castle": b'\xf0\x9f\x8f\xb0',
         "snail": b'\xf0\x9f\x90\x8c',
         "snake": b'\xf0\x9f\x90\x8d',
         "horse": b'\xf0\x9f\x90\x8e',
         "sheep": b'\xf0\x9f\x90\x91',
         "monkey": b'\xf0\x9f\x90\x92',
         "chicken": b'\xf0\x9f\x90\x94',
         "boar": b'\xf0\x9f\x90\x97',
         "elephant": b'\xf0\x9f\x90\x98',
         "octopus": b'\xf0\x9f\x90\x99',
         "spiral shell": b'\xf0\x9f\x90\x9a',
         "bug": b'\xf0\x9f\x90\x9b',
         "ant": b'\xf0\x9f\x90\x9c',
         "honeybee": b'\xf0\x9f\x90\x9d',
         "lady beetle": b'\xf0\x9f\x90\x9e',
         "fish": b'\xf0\x9f\x90\x9f',
         "tropical fish": b'\xf0\x9f\x90\xa0',
         "blowfish": b'\xf0\x9f\x90\xa1',
         "turtle": b'\xf0\x9f\x90\xa2',
         "hatching chick": b'\xf0\x9f\x90\xa3',
         "baby chick": b'\xf0\x9f\x90\xa4',
         "front-facing baby chick": b'\xf0\x9f\x90\xa5',
         "bird": b'\xf0\x9f\x90\xa6',
         "penguin": b'\xf0\x9f\x90\xa7',
         "koala": b'\xf0\x9f\x90\xa8',
         "poodle": b'\xf0\x9f\x90\xa9',
         "bactrian camel": b'\xf0\x9f\x90\xab',
         "dolphin": b'\xf0\x9f\x90\xac',
         "mouse face": b'\xf0\x9f\x90\xad',
         "cow face": b'\xf0\x9f\x90\xae',
         "tiger face": b'\xf0\x9f\x90\xaf',
         "rabbit face": b'\xf0\x9f\x90\xb0',
         "cat face": b'\xf0\x9f\x90\xb1',
         "dragon face": b'\xf0\x9f\x90\xb2',
         "spouting whale": b'\xf0\x9f\x90\xb3',
         "horse face": b'\xf0\x9f\x90\xb4',
         "monkey face": b'\xf0\x9f\x90\xb5',
         "dog face": b'\xf0\x9f\x90\xb6',
         "pig face": b'\xf0\x9f\x90\xb7',
         "frog face": b'\xf0\x9f\x90\xb8',
         "hamster face": b'\xf0\x9f\x90\xb9',
         "wolf face": b'\xf0\x9f\x90\xba',
         "bear face": b'\xf0\x9f\x90\xbb',
         "panda face": b'\xf0\x9f\x90\xbc',
         "pig nose": b'\xf0\x9f\x90\xbd',
         "paw prints": b'\xf0\x9f\x90\xbe',
         "eyes": b'\xf0\x9f\x91\x80',
         "ear": b'\xf0\x9f\x91\x82',
         "nose": b'\xf0\x9f\x91\x83',
         "mouth": b'\xf0\x9f\x91\x84',
         "tongue": b'\xf0\x9f\x91\x85',
         "white up pointing backhand index": b'\xf0\x9f\x91\x86',
         "white down pointing backhand index": b'\xf0\x9f\x91\x87',
         "white left pointing backhand index": b'\xf0\x9f\x91\x88',
         "white right pointing backhand index": b'\xf0\x9f\x91\x89',
         "fisted hand sign": b'\xf0\x9f\x91\x8a',
         "waving hand sign": b'\xf0\x9f\x91\x8b',
         "ok hand sign": b'\xf0\x9f\x91\x8c',
         "thumbs up sign": b'\xf0\x9f\x91\x8d',
         "thumbs down sign": b'\xf0\x9f\x91\x8e',
         "clapping hands sign": b'\xf0\x9f\x91\x8f',
         "open hands sign": b'\xf0\x9f\x91\x90',
         "crown": b'\xf0\x9f\x91\x91',
         "womans hat": b'\xf0\x9f\x91\x92',
         "eyeglasses": b'\xf0\x9f\x91\x93',
         "necktie": b'\xf0\x9f\x91\x94',
         "t-shirt": b'\xf0\x9f\x91\x95',
         "jeans": b'\xf0\x9f\x91\x96',
         "dress": b'\xf0\x9f\x91\x97',
         "kimono": b'\xf0\x9f\x91\x98',
         "bikini": b'\xf0\x9f\x91\x99',
         "womans clothes": b'\xf0\x9f\x91\x9a',
         "purse": b'\xf0\x9f\x91\x9b',
         "handbag": b'\xf0\x9f\x91\x9c',
         "pouch": b'\xf0\x9f\x91\x9d',
         "mans shoe": b'\xf0\x9f\x91\x9e',
         "athletic shoe": b'\xf0\x9f\x91\x9f',
         "high-heeled shoe": b'\xf0\x9f\x91\xa0',
         "womans sandal": b'\xf0\x9f\x91\xa1',
         "womans boots": b'\xf0\x9f\x91\xa2',
         "footprints": b'\xf0\x9f\x91\xa3',
         "bust in silhouette": b'\xf0\x9f\x91\xa4',
         "boy": b'\xf0\x9f\x91\xa6',
         "girl": b'\xf0\x9f\x91\xa7',
         "man": b'\xf0\x9f\x91\xa8',
         "woman": b'\xf0\x9f\x91\xa9',
         "family": b'\xf0\x9f\x91\xaa',
         "man and woman holding hands": b'\xf0\x9f\x91\xab',
         "police officer": b'\xf0\x9f\x91\xae',
         "woman with bunny ears": b'\xf0\x9f\x91\xaf',
         "bride with veil": b'\xf0\x9f\x91\xb0',
         "person with blond hair": b'\xf0\x9f\x91\xb1',
         "man with gua pi mao": b'\xf0\x9f\x91\xb2',
         "man with turban": b'\xf0\x9f\x91\xb3',
         "older man": b'\xf0\x9f\x91\xb4',
         "older woman": b'\xf0\x9f\x91\xb5',
         "baby": b'\xf0\x9f\x91\xb6',
         "construction worker": b'\xf0\x9f\x91\xb7',
         "princess": b'\xf0\x9f\x91\xb8',
         "japanese ogre": b'\xf0\x9f\x91\xb9',
         "japanese goblin": b'\xf0\x9f\x91\xba',
         "ghost": b'\xf0\x9f\x91\xbb',
         "baby angel": b'\xf0\x9f\x91\xbc',
         "extraterrestrial alien": b'\xf0\x9f\x91\xbd',
         "alien monster": b'\xf0\x9f\x91\xbe',
         "imp": b'\xf0\x9f\x91\xbf',
         "skull": b'\xf0\x9f\x92\x80',
         "information desk person": b'\xf0\x9f\x92\x81',
         "guardsman": b'\xf0\x9f\x92\x82',
         "dancer": b'\xf0\x9f\x92\x83',
         "lipstick": b'\xf0\x9f\x92\x84',
         "nail polish": b'\xf0\x9f\x92\x85',
         "face massage": b'\xf0\x9f\x92\x86',
         "haircut": b'\xf0\x9f\x92\x87',
         "barber pole": b'\xf0\x9f\x92\x88',
         "syringe": b'\xf0\x9f\x92\x89',
         "pill": b'\xf0\x9f\x92\x8a',
         "kiss mark": b'\xf0\x9f\x92\x8b',
         "love letter": b'\xf0\x9f\x92\x8c',
         "ring": b'\xf0\x9f\x92\x8d',
         "gem stone": b'\xf0\x9f\x92\x8e',
         "kiss": b'\xf0\x9f\x92\x8f',
         "bouquet": b'\xf0\x9f\x92\x90',
         "couple with heart": b'\xf0\x9f\x92\x91',
         "wedding": b'\xf0\x9f\x92\x92',
         "beating heart": b'\xf0\x9f\x92\x93',
         "broken heart": b'\xf0\x9f\x92\x94',
         "two hearts": b'\xf0\x9f\x92\x95',
         "sparkling heart": b'\xf0\x9f\x92\x96',
         "growing heart": b'\xf0\x9f\x92\x97',
         "heart with arrow": b'\xf0\x9f\x92\x98',
         "blue heart": b'\xf0\x9f\x92\x99',
         "green heart": b'\xf0\x9f\x92\x9a',
         "yellow heart": b'\xf0\x9f\x92\x9b',
         "purple heart": b'\xf0\x9f\x92\x9c',
         "heart with ribbon": b'\xf0\x9f\x92\x9d',
         "revolving hearts": b'\xf0\x9f\x92\x9e',
         "heart decoration": b'\xf0\x9f\x92\x9f',
         "diamond shape with a dot inside": b'\xf0\x9f\x92\xa0',
         "electric light bulb": b'\xf0\x9f\x92\xa1',
         "anger symbol": b'\xf0\x9f\x92\xa2',
         "bomb": b'\xf0\x9f\x92\xa3',
         "sleeping symbol": b'\xf0\x9f\x92\xa4',
         "collision symbol": b'\xf0\x9f\x92\xa5',
         "splashing sweat symbol": b'\xf0\x9f\x92\xa6',
         "droplet": b'\xf0\x9f\x92\xa7',
         "dash symbol": b'\xf0\x9f\x92\xa8',
         "pile of poo": b'\xf0\x9f\x92\xa9',
         "flexed biceps": b'\xf0\x9f\x92\xaa',
         "dizzy symbol": b'\xf0\x9f\x92\xab',
         "speech balloon": b'\xf0\x9f\x92\xac',
         "white flower": b'\xf0\x9f\x92\xae',
         "hundred points symbol": b'\xf0\x9f\x92\xaf',
         "money bag": b'\xf0\x9f\x92\xb0',
         "currency exchange": b'\xf0\x9f\x92\xb1',
         "heavy dollar sign": b'\xf0\x9f\x92\xb2',
         "credit card": b'\xf0\x9f\x92\xb3',
         "banknote with yen sign": b'\xf0\x9f\x92\xb4',
         "banknote with dollar sign": b'\xf0\x9f\x92\xb5',
         "money with wings": b'\xf0\x9f\x92\xb8',
         "chart with upwards trend and yen sign": b'\xf0\x9f\x92\xb9',
         "seat": b'\xf0\x9f\x92\xba',
         "personal computer": b'\xf0\x9f\x92\xbb',
         "briefcase": b'\xf0\x9f\x92\xbc',
         "minidisc": b'\xf0\x9f\x92\xbd',
         "floppy disk": b'\xf0\x9f\x92\xbe',
         "optical disc": b'\xf0\x9f\x92\xbf',
         "dvd": b'\xf0\x9f\x93\x80',
         "file folder": b'\xf0\x9f\x93\x81',
         "open file folder": b'\xf0\x9f\x93\x82',
         "page with curl": b'\xf0\x9f\x93\x83',
         "page facing up": b'\xf0\x9f\x93\x84',
         "calendar": b'\xf0\x9f\x93\x85',
         "tear-off calendar": b'\xf0\x9f\x93\x86',
         "card index": b'\xf0\x9f\x93\x87',
         "chart with upwards trend": b'\xf0\x9f\x93\x88',
         "chart with downwards trend": b'\xf0\x9f\x93\x89',
         "bar chart": b'\xf0\x9f\x93\x8a',
         "clipboard": b'\xf0\x9f\x93\x8b',
         "pushpin": b'\xf0\x9f\x93\x8c',
         "round pushpin": b'\xf0\x9f\x93\x8d',
         "paperclip": b'\xf0\x9f\x93\x8e',
         "straight ruler": b'\xf0\x9f\x93\x8f',
         "triangular ruler": b'\xf0\x9f\x93\x90',
         "bookmark tabs": b'\xf0\x9f\x93\x91',
         "ledger": b'\xf0\x9f\x93\x92',
         "notebook": b'\xf0\x9f\x93\x93',
         "notebook with decorative cover": b'\xf0\x9f\x93\x94',
         "closed book": b'\xf0\x9f\x93\x95',
         "open book": b'\xf0\x9f\x93\x96',
         "green book": b'\xf0\x9f\x93\x97',
         "blue book": b'\xf0\x9f\x93\x98',
         "orange book": b'\xf0\x9f\x93\x99',
         "books": b'\xf0\x9f\x93\x9a',
         "name badge": b'\xf0\x9f\x93\x9b',
         "scroll": b'\xf0\x9f\x93\x9c',
         "memo": b'\xf0\x9f\x93\x9d',
         "telephone receiver": b'\xf0\x9f\x93\x9e',
         "pager": b'\xf0\x9f\x93\x9f',
         "fax machine": b'\xf0\x9f\x93\xa0',
         "satellite antenna": b'\xf0\x9f\x93\xa1',
         "public address loudspeaker": b'\xf0\x9f\x93\xa2',
         "cheering megaphone": b'\xf0\x9f\x93\xa3',
         "outbox tray": b'\xf0\x9f\x93\xa4',
         "inbox tray": b'\xf0\x9f\x93\xa5',
         "package": b'\xf0\x9f\x93\xa6',
         "e-mail symbol": b'\xf0\x9f\x93\xa7',
         "incoming envelope": b'\xf0\x9f\x93\xa8',
         "envelope with downwards arrow above": b'\xf0\x9f\x93\xa9',
         "closed mailbox with lowered flag": b'\xf0\x9f\x93\xaa',
         "closed mailbox with raised flag": b'\xf0\x9f\x93\xab',
         "postbox": b'\xf0\x9f\x93\xae',
         "newspaper": b'\xf0\x9f\x93\xb0',
         "mobile phone": b'\xf0\x9f\x93\xb1',
         "mobile phone with rightwards arrow at left": b'\xf0\x9f\x93\xb2',
         "vibration mode": b'\xf0\x9f\x93\xb3',
         "mobile phone off": b'\xf0\x9f\x93\xb4',
         "antenna with bars": b'\xf0\x9f\x93\xb6',
         "camera": b'\xf0\x9f\x93\xb7',
         "video camera": b'\xf0\x9f\x93\xb9',
         "television": b'\xf0\x9f\x93\xba',
         "radio": b'\xf0\x9f\x93\xbb',
         "videocassette": b'\xf0\x9f\x93\xbc',
         "clockwise downwards and upwards open circle arrows": b'\xf0\x9f\x94\x83',
         "speaker with three sound waves": b'\xf0\x9f\x94\x8a',
         "battery": b'\xf0\x9f\x94\x8b',
         "electric plug": b'\xf0\x9f\x94\x8c',
         "left-pointing magnifying glass": b'\xf0\x9f\x94\x8d',
         "right-pointing magnifying glass": b'\xf0\x9f\x94\x8e',
         "lock with ink pen": b'\xf0\x9f\x94\x8f',
         "closed lock with key": b'\xf0\x9f\x94\x90',
         "key": b'\xf0\x9f\x94\x91',
         "lock": b'\xf0\x9f\x94\x92',
         "open lock": b'\xf0\x9f\x94\x93',
         "bell": b'\xf0\x9f\x94\x94',
         "bookmark": b'\xf0\x9f\x94\x96',
         "link symbol": b'\xf0\x9f\x94\x97',
         "radio button": b'\xf0\x9f\x94\x98',
         "back with leftwards arrow above": b'\xf0\x9f\x94\x99',
         "end with leftwards arrow above": b'\xf0\x9f\x94\x9a',
         "on with exclamation mark with left right arrow above": b'\xf0\x9f\x94\x9b',
         "soon with rightwards arrow above": b'\xf0\x9f\x94\x9c',
         "top with upwards arrow above": b'\xf0\x9f\x94\x9d',
         "no one under eighteen symbol": b'\xf0\x9f\x94\x9e',
         "keycap ten": b'\xf0\x9f\x94\x9f',
         "input symbol for latin capital letters": b'\xf0\x9f\x94\xa0',
         "input symbol for latin small letters": b'\xf0\x9f\x94\xa1',
         "input symbol for numbers": b'\xf0\x9f\x94\xa2',
         "input symbol for symbols": b'\xf0\x9f\x94\xa3',
         "input symbol for latin letters": b'\xf0\x9f\x94\xa4',
         "fire": b'\xf0\x9f\x94\xa5',
         "electric torch": b'\xf0\x9f\x94\xa6',
         "wrench": b'\xf0\x9f\x94\xa7',
         "hammer": b'\xf0\x9f\x94\xa8',
         "nut and bolt": b'\xf0\x9f\x94\xa9',
         "hocho": b'\xf0\x9f\x94\xaa',
         "pistol": b'\xf0\x9f\x94\xab',
         "crystal ball": b'\xf0\x9f\x94\xae',
         "six pointed star with middle dot": b'\xf0\x9f\x94\xaf',
         "japanese symbol for beginner": b'\xf0\x9f\x94\xb0',
         "trident emblem": b'\xf0\x9f\x94\xb1',
         "black square button": b'\xf0\x9f\x94\xb2',
         "white square button": b'\xf0\x9f\x94\xb3',
         "large red circle": b'\xf0\x9f\x94\xb4',
         "large blue circle": b'\xf0\x9f\x94\xb5',
         "large orange diamond": b'\xf0\x9f\x94\xb6',
         "large blue diamond": b'\xf0\x9f\x94\xb7',
         "small orange diamond": b'\xf0\x9f\x94\xb8',
         "small blue diamond": b'\xf0\x9f\x94\xb9',
         "up-pointing red triangle": b'\xf0\x9f\x94\xba',
         "down-pointing red triangle": b'\xf0\x9f\x94\xbb',
         "up-pointing small red triangle": b'\xf0\x9f\x94\xbc',
         "down-pointing small red triangle": b'\xf0\x9f\x94\xbd',
         "clock face one oclock": b'\xf0\x9f\x95\x90',
         "clock face two oclock": b'\xf0\x9f\x95\x91',
         "clock face three oclock": b'\xf0\x9f\x95\x92',
         "clock face four oclock": b'\xf0\x9f\x95\x93',
         "clock face five oclock": b'\xf0\x9f\x95\x94',
         "clock face six oclock": b'\xf0\x9f\x95\x95',
         "clock face seven oclock": b'\xf0\x9f\x95\x96',
         "clock face eight oclock": b'\xf0\x9f\x95\x97',
         "clock face nine oclock": b'\xf0\x9f\x95\x98',
         "clock face ten oclock": b'\xf0\x9f\x95\x99',
         "clock face eleven oclock": b'\xf0\x9f\x95\x9a',
         "clock face twelve oclock": b'\xf0\x9f\x95\x9b',
         "mount fuji": b'\xf0\x9f\x97\xbb',
         "tokyo tower": b'\xf0\x9f\x97\xbc',
         "statue of liberty": b'\xf0\x9f\x97\xbd',
         "silhouette of japan": b'\xf0\x9f\x97\xbe',
         "moyai": b'\xf0\x9f\x97\xbf',
         "grinning face": b'\xf0\x9f\x98\x80',
         "smiling face with halo": b'\xf0\x9f\x98\x87',
         "smiling face with horns": b'\xf0\x9f\x98\x88',
         "smiling face with sunglasses": b'\xf0\x9f\x98\x8e',
         "neutral face": b'\xf0\x9f\x98\x90',
         "expressionless face": b'\xf0\x9f\x98\x91',
         "confused face": b'\xf0\x9f\x98\x95',
         "kissing face": b'\xf0\x9f\x98\x97',
         "kissing face with smiling eyes": b'\xf0\x9f\x98\x99',
         "face with stuck-out tongue": b'\xf0\x9f\x98\x9b',
         "worried face": b'\xf0\x9f\x98\x9f',
         "frowning face with open mouth": b'\xf0\x9f\x98\xa6',
         "anguished face": b'\xf0\x9f\x98\xa7',
         "grimacing face": b'\xf0\x9f\x98\xac',
         "face with open mouth": b'\xf0\x9f\x98\xae',
         "hushed face": b'\xf0\x9f\x98\xaf',
         "sleeping face": b'\xf0\x9f\x98\xb4',
         "face without mouth": b'\xf0\x9f\x98\xb6',
         "helicopter": b'\xf0\x9f\x9a\x81',
         "steam locomotive": b'\xf0\x9f\x9a\x82',
         "train": b'\xf0\x9f\x9a\x86',
         "light rail": b'\xf0\x9f\x9a\x88',
         "tram": b'\xf0\x9f\x9a\x8a',
         "oncoming bus": b'\xf0\x9f\x9a\x8d',
         "trolleybus": b'\xf0\x9f\x9a\x8e',
         "minibus": b'\xf0\x9f\x9a\x90',
         "oncoming police car": b'\xf0\x9f\x9a\x94',
         "oncoming taxi": b'\xf0\x9f\x9a\x96',
         "oncoming automobile": b'\xf0\x9f\x9a\x98',
         "articulated lorry": b'\xf0\x9f\x9a\x9b',
         "tractor": b'\xf0\x9f\x9a\x9c',
         "monorail": b'\xf0\x9f\x9a\x9d',
         "mountain railway": b'\xf0\x9f\x9a\x9e',
         "suspension railway": b'\xf0\x9f\x9a\x9f',
         "mountain cableway": b'\xf0\x9f\x9a\xa0',
         "aerial tramway": b'\xf0\x9f\x9a\xa1',
         "rowboat": b'\xf0\x9f\x9a\xa3',
         "vertical traffic light": b'\xf0\x9f\x9a\xa6',
         "put litter in its place symbol": b'\xf0\x9f\x9a\xae',
         "do not litter symbol": b'\xf0\x9f\x9a\xaf',
         "potable water symbol": b'\xf0\x9f\x9a\xb0',
         "non-potable water symbol": b'\xf0\x9f\x9a\xb1',
         "no bicycles": b'\xf0\x9f\x9a\xb3',
         "bicyclist": b'\xf0\x9f\x9a\xb4',
         "mountain bicyclist": b'\xf0\x9f\x9a\xb5',
         "no pedestrians": b'\xf0\x9f\x9a\xb7',
         "children crossing": b'\xf0\x9f\x9a\xb8',
         "shower": b'\xf0\x9f\x9a\xbf',
         "bathtub": b'\xf0\x9f\x9b\x81',
         "passport control": b'\xf0\x9f\x9b\x82',
         "customs": b'\xf0\x9f\x9b\x83',
         "baggage claim": b'\xf0\x9f\x9b\x84',
         "left luggage": b'\xf0\x9f\x9b\x85',
         "earth globe europe-africa": b'\xf0\x9f\x8c\x8d',
         "earth globe americas": b'\xf0\x9f\x8c\x8e',
         "globe with meridians": b'\xf0\x9f\x8c\x90',
         "waxing crescent moon symbol": b'\xf0\x9f\x8c\x92',
         "waning gibbous moon symbol": b'\xf0\x9f\x8c\x96',
         "last quarter moon symbol": b'\xf0\x9f\x8c\x97',
         "waning crescent moon symbol": b'\xf0\x9f\x8c\x98',
         "new moon with face": b'\xf0\x9f\x8c\x9a',
         "last quarter moon with face": b'\xf0\x9f\x8c\x9c',
         "full moon with face": b'\xf0\x9f\x8c\x9d',
         "sun with face": b'\xf0\x9f\x8c\x9e',
         "evergreen tree": b'\xf0\x9f\x8c\xb2',
         "deciduous tree": b'\xf0\x9f\x8c\xb3',
         "lemon": b'\xf0\x9f\x8d\x8b',
         "pear": b'\xf0\x9f\x8d\x90',
         "baby bottle": b'\xf0\x9f\x8d\xbc',
         "horse racing": b'\xf0\x9f\x8f\x87',
         "rugby football": b'\xf0\x9f\x8f\x89',
         "european post office": b'\xf0\x9f\x8f\xa4',
         "rat": b'\xf0\x9f\x90\x80',
         "mouse": b'\xf0\x9f\x90\x81',
         "ox": b'\xf0\x9f\x90\x82',
         "water buffalo": b'\xf0\x9f\x90\x83',
         "cow": b'\xf0\x9f\x90\x84',
         "tiger": b'\xf0\x9f\x90\x85',
         "leopard": b'\xf0\x9f\x90\x86',
         "rabbit": b'\xf0\x9f\x90\x87',
         "cat": b'\xf0\x9f\x90\x88',
         "dragon": b'\xf0\x9f\x90\x89',
         "crocodile": b'\xf0\x9f\x90\x8a',
         "whale": b'\xf0\x9f\x90\x8b',
         "ram": b'\xf0\x9f\x90\x8f',
         "goat": b'\xf0\x9f\x90\x90',
         "rooster": b'\xf0\x9f\x90\x93',
         "dog": b'\xf0\x9f\x90\x95',
         "pig": b'\xf0\x9f\x90\x96',
         "dromedary camel": b'\xf0\x9f\x90\xaa',
         "busts in silhouette": b'\xf0\x9f\x91\xa5',
         "two men holding hands": b'\xf0\x9f\x91\xac',
         "two women holding hands": b'\xf0\x9f\x91\xad',
         "thought balloon": b'\xf0\x9f\x92\xad',
         "banknote with euro sign": b'\xf0\x9f\x92\xb6',
         "banknote with pound sign": b'\xf0\x9f\x92\xb7',
         "open mailbox with raised flag": b'\xf0\x9f\x93\xac',
         "open mailbox with lowered flag": b'\xf0\x9f\x93\xad',
         "postal horn": b'\xf0\x9f\x93\xaf',
         "no mobile phones": b'\xf0\x9f\x93\xb5',
         "twisted rightwards arrows": b'\xf0\x9f\x94\x80',
         "clockwise rightwards and leftwards open circle arrows": b'\xf0\x9f\x94\x81',
         "clockwise rightwards and leftwards open circle arrows with circled one overlay": b'\xf0\x9f\x94\x82',
         "anticlockwise downwards and upwards open circle arrows": b'\xf0\x9f\x94\x84',
         "low brightness symbol": b'\xf0\x9f\x94\x85',
         "high brightness symbol": b'\xf0\x9f\x94\x86',
         "speaker with cancellation stroke": b'\xf0\x9f\x94\x87',
         "speaker with one sound wave": b'\xf0\x9f\x94\x89',
         "bell with cancellation stroke": b'\xf0\x9f\x94\x95',
         "microscope": b'\xf0\x9f\x94\xac',
         "telescope": b'\xf0\x9f\x94\xad',
         "clock face one-thirty": b'\xf0\x9f\x95\x9c',
         "clock face two-thirty": b'\xf0\x9f\x95\x9d',
         "clock face three-thirty": b'\xf0\x9f\x95\x9e',
         "clock face four-thirty": b'\xf0\x9f\x95\x9f',
         "clock face five-thirty": b'\xf0\x9f\x95\xa0',
         "clock face six-thirty": b'\xf0\x9f\x95\xa1',
         "clock face seven-thirty": b'\xf0\x9f\x95\xa2',
         "clock face eight-thirty": b'\xf0\x9f\x95\xa3',
         "clock face nine-thirty": b'\xf0\x9f\x95\xa4',
         "clock face ten-thirty": b'\xf0\x9f\x95\xa5',
         "clock face eleven-thirty": b'\xf0\x9f\x95\xa6',
         "clock face twelve-thirty": b'\xf0\x9f\x95\xa7',
         "face with three hearts": b'\xf0\x9f\xa5\xb0'}

def emoji(name):
    return codes[name].decode("utf-8")

def flagEmoji(countryCode):
    key = "regional indicator symbol letter %s + regional indicator symbol letter %s" % (countryCode[0], countryCode[1])
    return emoji(key)

def getName(code):
    if type(code) == str:
        code = code.encode("utf-8")
    values = list(codes.values())
    if code in values:
        return list(codes.keys())[values.index(code)]
    return None
